// Single-letter prefixes for the marked inline extensions (`[k id Nom]`): a letter already taken sends the marker to another of the word's own — cLan, allIance.
export const INLINE_MARKER = {
  Alliance: 'i',
  Boat: 'o',
  Book: 'b',
  City: 'c',
  Clan: 'l',
  Culture: 't',
  Family: 'f',
  Kingdom: 'k',
  Language: 'a',
  Person: 'p',
  Religion: 'e',
  Resource: 'r',
  Species: 's',
  Subspecies: 'u',
  War: 'w',
} as const;

// Text hue per sapient species — all of `initCivsClassic`, `initCivsNew` and the `initMobsOther` civs. The four classics take the darkest of their
// canonical `preferred_colors` (WB's `initCivsClassic` IL, `colors_general`); the rest their icon's most saturated hue, darkened until it reads as text.
export const SPECIES_COLORS: Readonly<Record<string, string>> = {
  alien: '#5fc94a',
  angle: '#f5c63a',
  bandit: '#c14040',
  civ_acid_gentleman: '#70a040',
  civ_alpaca: '#bfbfb0',
  civ_armadillo: '#604020',
  civ_bear: '#402010',
  civ_beetle: '#301c1c',
  civ_buffalo: '#504030',
  civ_candy_man: '#b08040',
  civ_capybara: '#b06020',
  civ_cat: '#f0b050',
  civ_chicken: '#bfbfb0',
  civ_cow: '#203030',
  civ_crab: '#e05050',
  civ_crocodile: '#204030',
  civ_crystal_golem: '#a1cedc',
  civ_dog: '#402010',
  civ_fox: '#a04020',
  civ_frog: '#60a030',
  civ_garlic_man: '#d0c090',
  civ_goat: '#bfbfb0',
  civ_hyena: '#b06020',
  civ_lemon_man: '#caca35',
  civ_liliar: '#105040',
  civ_monkey: '#301c08',
  civ_penguin: '#301c1c',
  civ_piranha: '#507090',
  civ_rabbit: '#bdbdaf',
  civ_rat: '#30b020',
  civ_rhino: '#301c1c',
  civ_scorpion: '#b02030',
  civ_seal: '#203030',
  civ_sheep: '#b0c0a0',
  civ_snake: '#60a030',
  civ_turtle: '#305010',
  civ_unicorn: '#405070',
  civ_wolf: '#405060',
  cold_one: '#7ac8e3',
  demon: '#d33a2a',
  druid: '#7a9b3a',
  dwarf: '#9A6324', // preferred yellow/orange/brown
  elf: '#3CB44B', // preferred green/lime/lavender
  evil_mage: '#a83a6a',
  ghost: '#7a8a9c',
  human: '#00675C', // preferred blue/navy/teal/cyan
  necromancer: '#5a3a8e',
  orc: '#262626', // preferred red/orange/brown/maroon/black
  plague_doctor: '#2c3a4a',
  snowman: '#5a90b8',
  white_mage: '#c9a04a',
};
